import skincareStoryPhoto from '../assets/skincare_story_showcase.jpg';
import botanicalProductsPhoto from '../assets/login_botanical_products.jpg';
import heroImage from '../assets/heroimage.jpeg';

export const FALLBACK_CATEGORIES = [
  { id: 1, name: 'Herbal Extracts', slug: 'herbal-extracts', image_url: skincareStoryPhoto, is_active: 1, is_featured: 1 },
  { id: 2, name: 'Supplements', slug: 'supplements', image_url: botanicalProductsPhoto, is_active: 1, is_featured: 1 },
  { id: 3, name: 'Formulations', slug: 'biotech-formulations', image_url: heroImage, is_active: 1, is_featured: 1 },
  { id: 4, name: 'Skin Care', slug: 'skin-care-actives', image_url: skincareStoryPhoto, is_active: 1, is_featured: 1 },
  { id: 5, name: 'Face Creams', slug: 'face-creams', image_url: botanicalProductsPhoto, is_active: 1, is_featured: 1 },
  { id: 7, name: 'Moisturizers', slug: 'moisturizers', image_url: skincareStoryPhoto, is_active: 1, is_featured: 1 },
  { id: 8, name: 'Face Masks', slug: 'face-masks', image_url: heroImage, is_active: 1, is_featured: 0 },
  { id: 9, name: 'Sun Care', slug: 'sun-screens', image_url: botanicalProductsPhoto, is_active: 1, is_featured: 1 },
  { id: 10, name: 'Body Care', slug: 'body-care', image_url: skincareStoryPhoto, is_active: 1, is_featured: 1 },
];

export const FALLBACK_PRODUCTS = [
  {
    id: 1,
    name: 'LeafExtract Pharma Grades',
    brand: 'Leafora',
    sku: 'LFA-628708',
    category: 'Herbal Extracts',
    price: 49.99,
    originalPrice: 65.00,
    stock: 117,
    rating: '4.9',
    reviews: 64,
    badge: 'Best Seller',
    badgeType: 'bestseller',
    skinType: ['Normal', 'Dry', 'Combination'],
    concerns: ['Hydration', 'Brightening'],
    inStock: true,
    description: 'Pharma-grade pure organic botanical extract serum formulated for deep cellular rejuvenation.',
    image: skincareStoryPhoto,
    image_url: skincareStoryPhoto,
    images: [skincareStoryPhoto, botanicalProductsPhoto],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 2,
    name: 'BioVital Nutraceutical',
    brand: 'Leafora',
    sku: 'LFA-954068',
    category: 'Supplements',
    price: 29.50,
    originalPrice: 45.00,
    stock: 85,
    rating: '4.8',
    reviews: 52,
    badge: 'Trending',
    badgeType: 'trending',
    skinType: ['Normal', 'Dry', 'Sensitive'],
    concerns: ['Hydration', 'Anti-Aging'],
    inStock: true,
    description: 'Essential daily botanical vitamins and bio-vital nutraceutical minerals.',
    image: botanicalProductsPhoto,
    image_url: botanicalProductsPhoto,
    images: [botanicalProductsPhoto, skincareStoryPhoto],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 3,
    name: 'EcoScience Active Solution',
    brand: 'Leafora',
    sku: 'LFA-978964',
    category: 'Formulations',
    price: 89.00,
    originalPrice: 110.00,
    stock: 40,
    rating: '5.0',
    reviews: 88,
    badge: 'New',
    badgeType: 'new',
    skinType: ['Normal', 'Oily', 'Combination'],
    concerns: ['Brightening', 'Dark Spots'],
    inStock: true,
    description: 'Advanced biotech cellular active solution formulated for luminous complexion.',
    image: skincareStoryPhoto,
    image_url: skincareStoryPhoto,
    images: [skincareStoryPhoto, heroImage],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 4,
    name: 'Aloe Vera Pure Gel Base',
    brand: 'Leafora',
    sku: 'LFA-009724',
    category: 'Skin Care',
    price: 19.99,
    originalPrice: 28.00,
    stock: 8,
    rating: '4.7',
    reviews: 38,
    badge: null,
    skinType: ['Normal', 'Dry', 'Sensitive', 'Oily'],
    concerns: ['Hydration', 'Acne'],
    inStock: true,
    description: '100% pure cold-pressed organic aloe vera soothing gel for skin repair and calm.',
    image: botanicalProductsPhoto,
    image_url: botanicalProductsPhoto,
    images: [botanicalProductsPhoto],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 5,
    name: 'Curcumin 95% Extract',
    brand: 'Leafora',
    sku: 'LFA-050940',
    category: 'Herbal Extracts',
    price: 65.00,
    originalPrice: 80.00,
    stock: 0,
    rating: '4.9',
    reviews: 45,
    badge: 'Best Seller',
    badgeType: 'bestseller',
    skinType: ['Normal', 'Combination'],
    concerns: ['Anti-Aging', 'Brightening'],
    inStock: false,
    description: 'High potency 95% standardized curcuminoids extract for anti-inflammatory antioxidant care.',
    image: heroImage,
    image_url: heroImage,
    images: [heroImage, skincareStoryPhoto],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 6,
    name: 'Gentle Foaming Face Wash',
    brand: 'Leafora Clinical',
    sku: 'LFA-1662',
    category: 'Face Creams',
    price: 499.00,
    originalPrice: 599.00,
    stock: 98,
    rating: '4.8',
    reviews: 60,
    badge: 'New',
    badgeType: 'new',
    skinType: ['Normal', 'Oily', 'Sensitive', 'Combination'],
    concerns: ['Acne', 'Hydration'],
    inStock: true,
    description: 'Sulfate-free botanical gentle foaming face wash enriched with chamomile and green tea extract.',
    image: botanicalProductsPhoto,
    image_url: botanicalProductsPhoto,
    images: [botanicalProductsPhoto, heroImage],
    is_active: 1,
    is_featured: 0,
  },
];
