import skincareStoryPhoto from '../assets/skincare_story_showcase.jpg';
import botanicalProductsPhoto from '../assets/login_botanical_products.jpg';
import heroImage from '../assets/heroimage.jpeg';

export const FALLBACK_CATEGORIES = [
  { id: 1, name: 'Herbal Extracts', slug: 'herbal-extracts', is_active: 1, is_featured: 1 },
  { id: 2, name: 'Supplements', slug: 'supplements', is_active: 1, is_featured: 1 },
  { id: 3, name: 'Biotech Formulations', slug: 'biotech-formulations', is_active: 1, is_featured: 0 },
  { id: 4, name: 'Skin Care Actives', slug: 'skin-care-actives', is_active: 1, is_featured: 1 },
  { id: 5, name: 'Facial Serums', slug: 'facial-serums', is_active: 1, is_featured: 1 },
];

export const FALLBACK_PRODUCTS = [
  {
    id: 1,
    name: 'Pharma Grade LeafExtract Pure Actives',
    brand: 'Leafora',
    sku: 'LFA-EXT-01',
    category: 'Herbal Extracts',
    price: 49.99,
    originalPrice: 65.00,
    stock: 120,
    rating: '4.9',
    reviews: 64,
    badge: 'Best Seller',
    badgeType: 'bestseller',
    skinType: ['Normal', 'Dry', 'Combination'],
    concerns: ['Hydration', 'Brightening'],
    inStock: true,
    description: 'Pharma-grade pure organic botanical extract serum formulated for deep cellular rejuvenation.',
    image: skincareStoryPhoto,
    image_url: skincareStoryPhoto,
    images: [skincareStoryPhoto, botanicalProductsPhoto],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 2,
    name: 'BioVital Botanical Moisturizer',
    brand: 'Leafora',
    sku: 'LFA-MOIST-02',
    category: 'Skin Care Actives',
    price: 34.50,
    originalPrice: 45.00,
    stock: 85,
    rating: '4.8',
    reviews: 52,
    badge: 'Trending',
    badgeType: 'trending',
    skinType: ['Normal', 'Dry', 'Sensitive'],
    concerns: ['Hydration', 'Anti-Aging'],
    inStock: true,
    description: 'Deep hydration botanical face cream with natural hyaluronic acid and herbal extracts.',
    image: botanicalProductsPhoto,
    image_url: botanicalProductsPhoto,
    images: [botanicalProductsPhoto, skincareStoryPhoto],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 3,
    name: 'EcoScience Vitamin C Radiance Serum',
    brand: 'Leafora',
    sku: 'LFA-SERUM-03',
    category: 'Facial Serums',
    price: 59.00,
    originalPrice: 75.00,
    stock: 40,
    rating: '5.0',
    reviews: 88,
    badge: 'New',
    badgeType: 'new',
    skinType: ['Normal', 'Oily', 'Combination'],
    concerns: ['Brightening', 'Dark Spots'],
    inStock: true,
    description: 'Concentrated 20% Vitamin C serum with ferulic acid for bright, luminous complexion.',
    image: skincareStoryPhoto,
    image_url: skincareStoryPhoto,
    images: [skincareStoryPhoto, heroImage],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 4,
    name: 'Pure Organic Aloe Vera Actives Gel Base',
    brand: 'Leafora',
    sku: 'LFA-ALOE-04',
    category: 'Skin Care Actives',
    price: 19.99,
    originalPrice: 28.00,
    stock: 60,
    rating: '4.7',
    reviews: 38,
    badge: null,
    skinType: ['Normal', 'Dry', 'Sensitive', 'Oily'],
    concerns: ['Hydration', 'Acne'],
    inStock: true,
    description: '100% pure cold-pressed organic aloe vera soothing gel for skin repair and calm.',
    image: botanicalProductsPhoto,
    image_url: botanicalProductsPhoto,
    images: [botanicalProductsPhoto],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 5,
    name: 'Curcumin 95% Active Potency Extract',
    brand: 'Leafora',
    sku: 'LFA-CURC-05',
    category: 'Herbal Extracts',
    price: 65.00,
    originalPrice: 80.00,
    stock: 50,
    rating: '4.9',
    reviews: 45,
    badge: 'Best Seller',
    badgeType: 'bestseller',
    skinType: ['Normal', 'Combination'],
    concerns: ['Anti-Aging', 'Brightening'],
    inStock: true,
    description: 'High potency 95% standardized curcuminoids extract for anti-inflammatory antioxidant care.',
    image: heroImage,
    image_url: heroImage,
    images: [heroImage, skincareStoryPhoto],
    is_active: 1,
    is_featured: 1,
  },
  {
    id: 6,
    name: 'Gentle Botanical Cleansing Facial Wash',
    brand: 'Leafora',
    sku: 'LFA-WASH-06',
    category: 'Facial Serums',
    price: 24.99,
    originalPrice: 32.00,
    stock: 95,
    rating: '4.8',
    reviews: 60,
    badge: 'New',
    badgeType: 'new',
    skinType: ['Normal', 'Oily', 'Sensitive', 'Combination'],
    concerns: ['Acne', 'Hydration'],
    inStock: true,
    description: 'Sulfate-free botanical gel cleanser enriched with chamomile and green tea extract.',
    image: botanicalProductsPhoto,
    image_url: botanicalProductsPhoto,
    images: [botanicalProductsPhoto, heroImage],
    is_active: 1,
    is_featured: 0,
  },
];
